name: Draft Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  draft_action:
    if: "${{ startsWith(github.event.pull_request.head.ref, 'master') == false }}"
    name: PR Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check Event
        run: |
          git show
          echo "${{ toJson(github) }}"

      
