name: Draft Action

on:
  workflow_dispatch:
        
jobs:
  copy_deploy:
    name: Copy Deploy to Release
    runs-on: ubuntu-latest
    outputs:
      release-sha: ${{ steps.release-sha.outputs.sha }}
    steps:
      - name: Get Deploy SHA1
        id: master-sha
        run: |
          curl --fail --request GET 'https://api.github.com/repos/mateus-f-torres/echo/git/ref/heads/master' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: ${{ secrets.AUTOMATION_TOKEN }}' \
            --header 'Content-Type: application/json' | jq '.object.sha' > sha.txt
          echo "::set-output name=sha::$(cat sha.txt)"

      - name: Create Weekly Release Branch
        id: release-sha
        run: |
          data=$(cat <<EOF
          {
            "ref": "refs/heads/release/$(date +%y-%m-%d)",
            "sha": ${{ steps.master-sha.outputs.sha }}
          }
          EOF
          )

          curl --fail --request POST 'https://api.github.com/repos/mateus-f-torres/echo/git/refs' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: ${{ secrets.AUTOMATION_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data "$data" | jq '.object.sha' > sha.txt
          echo "::set-output name=sha::$(cat sha.txt)"

  release_pr:
    if: ${{ needs.copy_deploy.outputs.release-sha != null }}
    needs: copy_deploy
    name: Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.copy_deploy.outputs.release-sha }}
      - run: |
          echo ${{ needs.copy_deploy.outputs.release-sha }}
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      
