name: Draft Action

on:
  workflow_dispatch:
    # minute hour day_of_month (1-31) month (1-12) day_of_week (0-6)
    # 3 UTC = 0 Brasilia Time
    # 3 weekday = wednsday
    # - cron:  "0 14 * * 4"

jobs:
  draft_action:
    name: PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Get HEAD sha1
        id: master-sha
        run:  echo "sprint/$(date +%y-%m-%d)"
