name: Notify Active Fruits

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post active Fruits to API
        run: ./scripts/echo.sh
