name: Check PR Comment Body
#          echo "Comment on PR#${{ github.event.issue.number }}"
on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJson(github.event) }}"

      
