name: Pull Request Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  pull_request_action:
    name: Pull Request Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check Event
        run: |
          git show
          echo "${{ toJson(github) }}"


